### ISSUE TITLE
target_offset/source_offset in input/output in groups?

### ISSUE THREAD

**Issue by birgerjohansson** [ikaros-project/ikaros#85] opened 2019-02-12 13:16 UTC
Should it be possible to set offset in group input tags? Similar as in connections.

**Comment by ikaros-project** [comment] 2019-02-13 23:22
Duplicate of #81

**Comment by birgerjohansson** [comment] 2021-12-06 07:45
I think this is conceptually important. We need to implement this or make it clear that the source offset features does not apply for inputs. A workaround would be to use absolute paths into the group.

**Comment by ikaros-project** [comment] 2024-08-04 14:46
Handled by internal group connections in version 3.

**Closed** 2024-08-04 14:47 UTC
Labels: feature request, v2
